version: "3.5"
services:
  pg_master:
    build: ./master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hamed
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hamed
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    networks:
      - pg_cluster

  pg_slave:
    build: ./slave
    environment:
       - POSTGRES_USER=hamed
       - POSTGRES_PASSWORD=123456
       - POSTGRES_DB=hamed
       - PG_REP_USER=rep
       - PG_REP_PASSWORD=123456
    networks:
      - pg_cluster


networks:
  pg_cluster:
    
volumes:
  pg_data: